steps:
  - name: 'gcr.io/cloud-builders/gcloud@sha256:da28bd8b5e58e7ec2a8349a009e9f8cffe4c16f4537a3fc5756bcfaf121b58f0'
    args: [ 'kms', 'decrypt',
            '--ciphertext-file=cabal.config.enc',
            '--plaintext-file=/builder/home/.cabal/config',
            '--location=global',
            '--keyring=hackage',
            '--key=cabal-config' ]
    volumes:
      - name: cabal-config
        path: /builder/home/.cabal

  - name: 'haskell@sha256:406d59e658af4f0e9f490bc41bedf633040170a744f97a90ecfc52a29ddd99a9'
    args: [ 'cabal', 'new-sdist' ]

  - name: 'haskell@sha256:406d59e658af4f0e9f490bc41bedf633040170a744f97a90ecfc52a29ddd99a9'
    args: [ 'cabal', 'upload', '--publish', '/workspace/dist-newstyle/sdist/siren-json-$TAG_NAME.tar.gz' ]
    volumes:
      - name: cabal-config
        path: /builder/home/.cabal
