steps:
  - name: 'gcr.io/cloud-builders/gcloud@sha256:9738f30b4f091fe5ad4b697efb3b644395391bf18119f4690f640f70add7c4f6'
    args: [ 'kms', 'decrypt',
            '--ciphertext-file=cabal.config.enc',
            '--plaintext-file=/builder/home/.cabal/config',
            '--location=global',
            '--keyring=hackage',
            '--key=cabal-config' ]
    volumes:
      - name: cabal-config
        path: /builder/home/.cabal

  - name: 'haskell@sha256:406d59e658af4f0e9f490bc41bedf633040170a744f97a90ecfc52a29ddd99a9'
    args: [ 'cabal', 'new-sdist' ]

  - name: 'haskell@sha256:406d59e658af4f0e9f490bc41bedf633040170a744f97a90ecfc52a29ddd99a9'
    args: [ 'cabal', 'upload', '--publish', '/workspace/dist-newstyle/sdist/siren-json-$TAG_NAME.tar.gz' ]
    volumes:
      - name: cabal-config
        path: /builder/home/.cabal
