cabal-version:       3.0
name:                siren-json
version:             0.3.1.1
synopsis:            Siren Tools for Haskell

description:
  Types, classes, and functions for using the Siren—Hypermedia Type in Haskell.

homepage:            https://github.com/alunduil/siren-json.hs
bug-reports:         https://github.com/alunduil/siren-json.hs/issues
license:             MIT
license-file:        LICENSE
author:              Alex Brandt
maintainer:          alunduil@alunduil.com
copyright:           (c) 2017 Alex Brandt
category:            Data
build-type:          Simple
tested-with:         GHC == 9.6.*
                   , GHC == 9.8.*
                   , GHC == 9.10.*
                   , GHC == 9.12.*
                   , GHC == 9.14.*

extra-doc-files:
    CHANGELOG.md
  , COPYRIGHT
  , README.md

extra-source-files:
    Setup.hs

source-repository head
  type:     git
  location: https://github.com/alunduil/siren-json.hs
  branch:   main

common warnings
  ghc-options: -Wall
               -Wcompat
               -Widentities
               -Wincomplete-record-updates
               -Wincomplete-uni-patterns
               -Wpartial-fields
               -Wredundant-constraints

common language
  default-language: Haskell2010

common deps
  build-depends:
      aeson       >= 2.2  && < 2.4
    , base        >= 4.18 && < 4.23
    , bytestring  >= 0.11 && < 0.13
    , containers  >= 0.6  && < 0.9
    , http-media  >= 0.8  && < 0.9
    , http-types  >= 0.12 && < 0.13
    , network-uri >= 2.6  && < 2.7
    , text        >= 2.0  && < 2.2

library
  import:           warnings, language, deps

  hs-source-dirs:   src

  exposed-modules:
      Data.SirenJSON
    , External.Network.HTTP.Media.MediaType.JSON
    , External.Network.HTTP.Types.Method.JSON

  other-extensions:
      LambdaCase
    , OverloadedStrings
    , RecordWildCards

test-suite siren-json-tests
  import:           warnings, language, deps
  type:             exitcode-stdio-1.0
  main-is:          Main.hs

  hs-source-dirs:   test

  other-modules:
      Data.SirenJSON.Arbitrary
    , Data.SirenJSON.Norm
    , Data.SirenJSONTest
    , External.Network.HTTP.Media.MediaType.JSONTest
    , External.Network.HTTP.Types.Method.JSONTest

  build-depends:
      network-arbitrary    >= 1.0  && < 1.1
    , QuickCheck           >= 2.14 && < 2.19
    , quickcheck-instances >= 0.3  && < 0.5
    , siren-json
    , tasty                >= 1.5  && < 1.6
    , tasty-hunit          >= 0.10 && < 0.11
    , tasty-quickcheck     >= 0.10 && < 0.12
    , test-invariant       >= 0.4  && < 0.5

  other-extensions:
      OverloadedStrings
    , RecordWildCards
